include theos/makefiles/common.mk

APPLICATION_NAME = SSLKillSwitchTestApplication
SSLKillSwitchTestApplication_FILES = main.m SSLKillSwitchTestApplication.mm RootViewController.mm TestSSLKillSwitch.m
SSLKillSwitchTestApplication_FRAMEWORKS = UIKit CoreGraphics Security CFNetwork

include $(THEOS_MAKE_PATH)/application.mk
